### ISSUE TITLE
The pull-request-responsibility action is failing

### ISSUE THREAD

**Issue by ansasaki** [actions-automation/pull-request-responsibility#3]
Since few hours ago we are seeing errors like this in `rust-keylime` repo:
```
Run if [[ "request,assign,copy-labels-linked" =~ (^|,)"request"(,|$) ]]; then
  if [[ "request,assign,copy-labels-linked" =~ (^|,)"request"(,|$) ]]; then
    echo " --- REQUEST --- " && $GITHUB_ACTION_PATH/src/request "" "rust-team" "3"
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BOT_TOKEN: ***
 --- REQUEST --- 
Traceback (most recent call last):
  File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 205, in <module>
    main()
  File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 202, in main
    auto_request(pr=pr, org=org, token=token, team_name=team_name, num_to_request=num_to_request)
  File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 139, in auto_request
    login_to_id = {u["login"]: u["id"] for u in iterusers(pr_data)}
  File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 139, in <dictcomp>
    login_to_id = {u["login"]: u["id"] for u in iterusers(pr_data)}
KeyError: 'login'
```
Apparently something changed on the `githubgql.graphql()` output.

**Comment by ansasaki** [comment]
Closing this as apparently the problem is gone.
